package aa.bb.cc.web.nls;

import java.util.Locale;
import java.util.ResourceBundle;

/*
 * auto generated by Messages.properties 
 */
public class Messages {

	protected MessageHolder holder = new MessageHolder();

	public Messages() {
		holder.add(ResourceBundle.getBundle(Messages.class.getName()));
	}

	public String ERROR_REQUIRED() {
		return ERROR_REQUIRED(Locale.getDefault());
	}

	public String ERROR_REQUIRED(Locale l) {
		return holder.getMessage(l, "ERROR_REQUIRED");
	}
}
