CREATE TABLE IF NOT EXISTS ARTIFACT (
	ID IDENTITY PRIMARY KEY 
	,GROUP_ID VARCHAR(255)
	,ARTIFACT_ID VARCHAR(255)
	,VERSION VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS DEPENDENCY (
	ID IDENTITY PRIMARY KEY 
	,FROM_ARTIFACT_ID VARCHAR(255)
	,TO_ARTIFACT_ID VARCHAR(255)
	,OPTIONAL BOOLEAN
);