SELECT GROUP_ID, ARTIFACT_ID, VERSION, OPTIONAL 
FROM ARTIFACT, (
SELECT TO_ARTIFACT_ID,DEP.OPTIONAL 
FROM 
ARTIFACT INNER JOIN DEPENDENCY DEP ON ARTIFACT.ID = DEP.FROM_ARTIFACT_ID 
WHERE 
GROUP_ID =? AND 
ARTIFACT_ID =? AND  
VERSION = ? 
) D 
WHERE ARTIFACT.ID = D.TO_ARTIFACT_ID