// Generated by the protocol buffer compiler.  DO NOT EDIT!

package org.handwerkszeug.kvsview.pb;

public final class TestPB {
  private TestPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Dept extends
      com.google.protobuf.GeneratedMessage {
    // Use Dept.newBuilder() to construct.
    private Dept() {}
    
    private static final Dept defaultInstance = new Dept();
    public static Dept getDefaultInstance() {
      return defaultInstance;
    }
    
    public Dept getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.handwerkszeug.kvsview.pb.TestPB.internal_static_kvsview_test_Dept_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.handwerkszeug.kvsview.pb.TestPB.internal_static_kvsview_test_Dept_fieldAccessorTable;
    }
    
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private long id_ = 0L;
    public boolean hasId() { return hasId; }
    public long getId() { return id_; }
    
    // required string deptName = 2;
    public static final int DEPTNAME_FIELD_NUMBER = 2;
    private boolean hasDeptName;
    private java.lang.String deptName_ = "";
    public boolean hasDeptName() { return hasDeptName; }
    public java.lang.String getDeptName() { return deptName_; }
    
    public final boolean isInitialized() {
      if (!hasId) return false;
      if (!hasDeptName) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasId()) {
        output.writeInt64(1, getId());
      }
      if (hasDeptName()) {
        output.writeString(2, getDeptName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, getId());
      }
      if (hasDeptName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getDeptName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.handwerkszeug.kvsview.pb.TestPB.Dept parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.handwerkszeug.kvsview.pb.TestPB.Dept parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.handwerkszeug.kvsview.pb.TestPB.Dept parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.handwerkszeug.kvsview.pb.TestPB.Dept parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.handwerkszeug.kvsview.pb.TestPB.Dept parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.handwerkszeug.kvsview.pb.TestPB.Dept parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.handwerkszeug.kvsview.pb.TestPB.Dept parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static org.handwerkszeug.kvsview.pb.TestPB.Dept parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.handwerkszeug.kvsview.pb.TestPB.Dept parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.handwerkszeug.kvsview.pb.TestPB.Dept parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.handwerkszeug.kvsview.pb.TestPB.Dept prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.handwerkszeug.kvsview.pb.TestPB.Dept result;
      
      // Construct using org.handwerkszeug.kvsview.pb.TestPB.Dept.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.handwerkszeug.kvsview.pb.TestPB.Dept();
        return builder;
      }
      
      protected org.handwerkszeug.kvsview.pb.TestPB.Dept internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.handwerkszeug.kvsview.pb.TestPB.Dept();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.handwerkszeug.kvsview.pb.TestPB.Dept.getDescriptor();
      }
      
      public org.handwerkszeug.kvsview.pb.TestPB.Dept getDefaultInstanceForType() {
        return org.handwerkszeug.kvsview.pb.TestPB.Dept.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.handwerkszeug.kvsview.pb.TestPB.Dept build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.handwerkszeug.kvsview.pb.TestPB.Dept buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.handwerkszeug.kvsview.pb.TestPB.Dept buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        org.handwerkszeug.kvsview.pb.TestPB.Dept returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.handwerkszeug.kvsview.pb.TestPB.Dept) {
          return mergeFrom((org.handwerkszeug.kvsview.pb.TestPB.Dept)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.handwerkszeug.kvsview.pb.TestPB.Dept other) {
        if (other == org.handwerkszeug.kvsview.pb.TestPB.Dept.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasDeptName()) {
          setDeptName(other.getDeptName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt64());
              break;
            }
            case 18: {
              setDeptName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required int64 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public long getId() {
        return result.getId();
      }
      public Builder setId(long value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0L;
        return this;
      }
      
      // required string deptName = 2;
      public boolean hasDeptName() {
        return result.hasDeptName();
      }
      public java.lang.String getDeptName() {
        return result.getDeptName();
      }
      public Builder setDeptName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDeptName = true;
        result.deptName_ = value;
        return this;
      }
      public Builder clearDeptName() {
        result.hasDeptName = false;
        result.deptName_ = getDefaultInstance().getDeptName();
        return this;
      }
    }
    
    static {
      org.handwerkszeug.kvsview.pb.TestPB.getDescriptor();
    }
    
    static {
      org.handwerkszeug.kvsview.pb.TestPB.internalForceInit();
    }
  }
  
  public static final class Emp extends
      com.google.protobuf.GeneratedMessage {
    // Use Emp.newBuilder() to construct.
    private Emp() {}
    
    private static final Emp defaultInstance = new Emp();
    public static Emp getDefaultInstance() {
      return defaultInstance;
    }
    
    public Emp getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.handwerkszeug.kvsview.pb.TestPB.internal_static_kvsview_test_Emp_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.handwerkszeug.kvsview.pb.TestPB.internal_static_kvsview_test_Emp_fieldAccessorTable;
    }
    
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private long id_ = 0L;
    public boolean hasId() { return hasId; }
    public long getId() { return id_; }
    
    // required string empName = 2;
    public static final int EMPNAME_FIELD_NUMBER = 2;
    private boolean hasEmpName;
    private java.lang.String empName_ = "";
    public boolean hasEmpName() { return hasEmpName; }
    public java.lang.String getEmpName() { return empName_; }
    
    // required .kvsview.test.Dept dept = 3;
    public static final int DEPT_FIELD_NUMBER = 3;
    private boolean hasDept;
    private org.handwerkszeug.kvsview.pb.TestPB.Dept dept_ = org.handwerkszeug.kvsview.pb.TestPB.Dept.getDefaultInstance();
    public boolean hasDept() { return hasDept; }
    public org.handwerkszeug.kvsview.pb.TestPB.Dept getDept() { return dept_; }
    
    public final boolean isInitialized() {
      if (!hasId) return false;
      if (!hasEmpName) return false;
      if (!hasDept) return false;
      if (!getDept().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasId()) {
        output.writeInt64(1, getId());
      }
      if (hasEmpName()) {
        output.writeString(2, getEmpName());
      }
      if (hasDept()) {
        output.writeMessage(3, getDept());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, getId());
      }
      if (hasEmpName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getEmpName());
      }
      if (hasDept()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getDept());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.handwerkszeug.kvsview.pb.TestPB.Emp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.handwerkszeug.kvsview.pb.TestPB.Emp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.handwerkszeug.kvsview.pb.TestPB.Emp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.handwerkszeug.kvsview.pb.TestPB.Emp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.handwerkszeug.kvsview.pb.TestPB.Emp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.handwerkszeug.kvsview.pb.TestPB.Emp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.handwerkszeug.kvsview.pb.TestPB.Emp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static org.handwerkszeug.kvsview.pb.TestPB.Emp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.handwerkszeug.kvsview.pb.TestPB.Emp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.handwerkszeug.kvsview.pb.TestPB.Emp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.handwerkszeug.kvsview.pb.TestPB.Emp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.handwerkszeug.kvsview.pb.TestPB.Emp result;
      
      // Construct using org.handwerkszeug.kvsview.pb.TestPB.Emp.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.handwerkszeug.kvsview.pb.TestPB.Emp();
        return builder;
      }
      
      protected org.handwerkszeug.kvsview.pb.TestPB.Emp internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.handwerkszeug.kvsview.pb.TestPB.Emp();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.handwerkszeug.kvsview.pb.TestPB.Emp.getDescriptor();
      }
      
      public org.handwerkszeug.kvsview.pb.TestPB.Emp getDefaultInstanceForType() {
        return org.handwerkszeug.kvsview.pb.TestPB.Emp.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.handwerkszeug.kvsview.pb.TestPB.Emp build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.handwerkszeug.kvsview.pb.TestPB.Emp buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.handwerkszeug.kvsview.pb.TestPB.Emp buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        org.handwerkszeug.kvsview.pb.TestPB.Emp returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.handwerkszeug.kvsview.pb.TestPB.Emp) {
          return mergeFrom((org.handwerkszeug.kvsview.pb.TestPB.Emp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.handwerkszeug.kvsview.pb.TestPB.Emp other) {
        if (other == org.handwerkszeug.kvsview.pb.TestPB.Emp.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasEmpName()) {
          setEmpName(other.getEmpName());
        }
        if (other.hasDept()) {
          mergeDept(other.getDept());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt64());
              break;
            }
            case 18: {
              setEmpName(input.readString());
              break;
            }
            case 26: {
              org.handwerkszeug.kvsview.pb.TestPB.Dept.Builder subBuilder = org.handwerkszeug.kvsview.pb.TestPB.Dept.newBuilder();
              if (hasDept()) {
                subBuilder.mergeFrom(getDept());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setDept(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int64 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public long getId() {
        return result.getId();
      }
      public Builder setId(long value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0L;
        return this;
      }
      
      // required string empName = 2;
      public boolean hasEmpName() {
        return result.hasEmpName();
      }
      public java.lang.String getEmpName() {
        return result.getEmpName();
      }
      public Builder setEmpName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasEmpName = true;
        result.empName_ = value;
        return this;
      }
      public Builder clearEmpName() {
        result.hasEmpName = false;
        result.empName_ = getDefaultInstance().getEmpName();
        return this;
      }
      
      // required .kvsview.test.Dept dept = 3;
      public boolean hasDept() {
        return result.hasDept();
      }
      public org.handwerkszeug.kvsview.pb.TestPB.Dept getDept() {
        return result.getDept();
      }
      public Builder setDept(org.handwerkszeug.kvsview.pb.TestPB.Dept value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasDept = true;
        result.dept_ = value;
        return this;
      }
      public Builder setDept(org.handwerkszeug.kvsview.pb.TestPB.Dept.Builder builderForValue) {
        result.hasDept = true;
        result.dept_ = builderForValue.build();
        return this;
      }
      public Builder mergeDept(org.handwerkszeug.kvsview.pb.TestPB.Dept value) {
        if (result.hasDept() &&
            result.dept_ != org.handwerkszeug.kvsview.pb.TestPB.Dept.getDefaultInstance()) {
          result.dept_ =
            org.handwerkszeug.kvsview.pb.TestPB.Dept.newBuilder(result.dept_).mergeFrom(value).buildPartial();
        } else {
          result.dept_ = value;
        }
        result.hasDept = true;
        return this;
      }
      public Builder clearDept() {
        result.hasDept = false;
        result.dept_ = org.handwerkszeug.kvsview.pb.TestPB.Dept.getDefaultInstance();
        return this;
      }
    }
    
    static {
      org.handwerkszeug.kvsview.pb.TestPB.getDescriptor();
    }
    
    static {
      org.handwerkszeug.kvsview.pb.TestPB.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_kvsview_test_Dept_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_kvsview_test_Dept_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_kvsview_test_Emp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_kvsview_test_Emp_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021test_entity.proto\022\014kvsview.test\"$\n\004Dep" +
      "t\022\n\n\002id\030\001 \002(\003\022\020\n\010deptName\030\002 \002(\t\"D\n\003Emp\022\n" +
      "\n\002id\030\001 \002(\003\022\017\n\007empName\030\002 \002(\t\022 \n\004dept\030\003 \002(" +
      "\0132\022.kvsview.test.DeptB(\n\034org.handwerksze" +
      "ug.kvsview.pbB\006TestPBH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_kvsview_test_Dept_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_kvsview_test_Dept_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_kvsview_test_Dept_descriptor,
              new java.lang.String[] { "Id", "DeptName", },
              org.handwerkszeug.kvsview.pb.TestPB.Dept.class,
              org.handwerkszeug.kvsview.pb.TestPB.Dept.Builder.class);
          internal_static_kvsview_test_Emp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_kvsview_test_Emp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_kvsview_test_Emp_descriptor,
              new java.lang.String[] { "Id", "EmpName", "Dept", },
              org.handwerkszeug.kvsview.pb.TestPB.Emp.class,
              org.handwerkszeug.kvsview.pb.TestPB.Emp.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
